### ISSUE TITLE
Unlinked AutoPortals running r portal fastpath 0 on map load

### ISSUE THREAD

**Issue by Komos63** [AxoLabs/BEE2-Axos-Packages#12]
### Describe the improvement
Having the AutoPortals automatically run r_portal_fastpath 0 on map load

### Why do you think this should be added
This would fix graphical issues in several situations, such as
- Placing 2+ pairs of AutoPortals and the pair shot by the gun in singleplayer
- Placing any amount of AutoPortals in coop and having both player's portals be rendered

### Additional information
There's a WorldPortal fixer item in the UCP pack which already does this, perhaps you could use something similar to that. People might not know that this is needed for 5+ portals so integrating it into the AutoPortals would help.

**Comment by AxoLabs** [comment]
Since as you stated yourself there's an item that does that, I don't see a point in implementing this.
