### ISSUE TITLE
Schrödinger Cube's effects break while inside a portal.

### ISSUE THREAD

**Issue by Komos63** [AxoLabs/BEE2-Axos-Packages#13]
### BEEMod version
4.43.0 App, 4.43.0 Packages

### UCP version
1.7.1
### Describe the bug
While a Schrödinger cube is inside of a portal, the green effect only shows up on one side.

### Steps to reproduce
Place 2 portals
Place Schrödinger Cube inside (Doesn't matter if it's an emitter or a catcher)
-> The green effect is only visible on one side of the portal. The other side looks like a redirection cube.

### Additional Information
Recoloring the cube using an ent_fire command (Found a guide! https://steamcommunity.com/sharedfiles/filedetails/?id=1183526436) instead of using Sendificator models could potentially fix the issue. However, this would make the cubes look different than they do now. Perhaps you could use both ent_fire and the sendificator effect to keep them green while inside a portal and keep the effect while outside of portals?

**Comment by AxoLabs** [comment]
Not significant enough to even consider fixing.
