### ISSUE TITLE
Cant find a way to use schrodinger's cube 

### ISSUE THREAD

**Issue by Grump-Mcdump** [AxoLabs/BEE2-Axos-Packages#20]
Cant find a option to change the cube into a catcher or emitter and both of them just block the laser like a normal cube.

**Comment by AxoLabs** [comment]
The separation of the cubes into catcher and emitter was removed in version 1.9.2, they essentially work more or less the same way they do in base Portal 2 now. Please check the changelog next time before opening an issue.
