### ISSUE TITLE
Schrödinger Cube connectability

### ISSUE THREAD

**Issue by Komos63** [AxoLabs/BEE2-Axos-Packages#6]
### Describe the improvement
Being able to connect a pair of Schrödinger Cubes would be useful as you could have more than a single pair per chamber.

### Why do you think this should be added
It would make the cubes more useful. You could also use different colors for the different pairs instead of only green to differentiate which pair will activate.

**Comment by AxoLabs** [comment]
While it would be useful, and was very much of in my plans for the release

**Comment by Komos63** [comment]
Is it possible to colorise the different pairs depending on what cube they're connected to? Otherwise it might be easy to get confused. For example 2 green cubes would link together, 2 blue cubes would link together instead of 2 green cubes and 2 other green cubes

**Comment by AxoLabs** [comment]
The ability to connect them is intended to be used for multi-chamber maps. On the matter of colorizing them, read my initial comment.

And please don't post on closed issues. Thank you in advance.
