### ISSUE TITLE
Schrödinger Cubes can activate themselves

### ISSUE THREAD

**Issue by Komos63** [AxoLabs/BEE2-Axos-Packages#9]
### BEEMod version
2.4.43.0

### UCP version
1.5 beta 7
### Describe the bug
Emitter Schrödinger cubes can power their own catcher cube, letting them move away from the source laser and effectively creating a loop. This can be abused to bring lasers anywhere, letting you activate any laser relay as long as you can have both cubes face towards each other.

### Steps to reproduce
Place laser on ceilling
Place catcher cube underneath
Place emitter cube somewhere else, pointing towards the catcher cube
You can now move the catcher cube closer to the emitter cube, away from the source laser. If you rotate you can also move it across different directions.

### Additional Information
I am not 100% sure if this is intentional or not, it lets you make some new puzzles but also breaks others.

**Comment by AxoLabs** [comment]
_Schrödingus' Bootstraps_, as I call them, are very much of intentional.
